[tool.black]
line-length = 100
target-version = ["py311", "py312", "py313"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
target-version = "py311"
lint.extend-select = ["E", "F", "I"]
lint.ignore = ["E501"]  # 行長由 black 控制
fix = true
