model:
  vocab_size: 256
  d_model: 256
  n_heads: 8
  n_layers: 4
  d_ff: 1024
  dropout: 0.1
  max_seq_len: 256
  # BitNet 參數
  bitnet_variant: "1b"   # 1b or 1p58
  act_bits: 8
  group_size: 64
  use_rope: false        # char-level 可關閉

train:
  batch_size: 64
  lr: 3.0e-4
  weight_decay: 0.01
  epochs: 3
  eval_interval: 200
  seed: 42

runtime:
  dtype: bf16
